module ui.ExportHTML;
/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;
import com.skinconsortium.d.model.ModelContainer,
	   com.skinconsortium.d.commons.ConfigFile;
import model.XmlModel;
import model.StringUtils; // TODO CLEANUP

import PU = tango.util.PathUtil;
import tango.io.Path;

import dfl.internal.winapi;
import tango.stdc.stringz;

class ExportHTML: dfl.form.Form
{
	public char[] FILE_FILTER = "HTML Website (*.html)|*.html|All files (*.*)|*.*";
	public char[] DEFAULT_SAVE_EXTENSION = ".html";	
	
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.groupbox.GroupBox groupBox1;
	dfl.textbox.TextBox editTitle;
	dfl.panel.Panel panel2;
	dfl.groupbox.GroupBox groupBox2;
	dfl.button.Button btnBrowse;
	dfl.panel.Panel panel3;
	dfl.textbox.TextBox editFilename;
	dfl.button.Button btnExport;
	dfl.button.Button btnCancel;
	dfl.button.CheckBox chkBrowser;
	//~Entice Designer variables end here.
	
	IModelContainer mc;
	
	
	this(IModelContainer mc)
	{
		initializeExportHTML();
		
		//@  Other ExportHTML initialization code here.
		
		this.dockPadding.all = 6;
		
		this.cancelButton = btnCancel;
		this.acceptButton = btnExport;
		this.mc = mc;

		btnExport.click ~= &exportClick;
		btnBrowse.click ~= &browseClick;
		
		XmlModel model = cast(XmlModel)mc.getModel();
		
		this.editTitle.text = model.exportTitle;
		this.editFilename.text = model.exportFilename;	
		
		chkBrowser.checked = ConfigFile.getValue("exportOpenBrowser", true);
		
	}
	
	private void exportClick(Object sender, EventArgs ea)
	{
		XmlModel model = cast(XmlModel)mc.getModel();
		
		model.exportTitle = this.editTitle.text;
		model.exportFilename = this.editFilename.text;
		
		if (this.editTitle.text is null || this.editTitle.text == "")
		{
			return;
		}
		
		if (this.editFilename.text is null || this.editFilename.text == "")
		{
			return;
		}
		
		auto fp = new tango.io.FilePath.FilePath(this.editFilename.text);
		bool existed = fp.exists;
		if (!existed)
		{
			fp.createFile;
		}
		
		auto file = new tango.io.File.File(fp.toString());
		auto doc = new tango.text.xml.Document.Document!(char);
		
		auto htmlE = doc.root.element(null, "html");
		htmlE.element(null, "title", model.exportTitle);
		auto bodyE = htmlE.element(null, "body");
		
		bodyE.element(null, "h1", model.exportTitle);
		
		foreach(char[] key, char[] value; model.getMap())
		{
			bodyE.element(null, "h2", key);
			bodyE.element(null, "p", nlToBr!(char)(value));
		}
		
		auto print = new tango.text.xml.DocPrinter.DocPrinter!(char);
		file.write(cast(void[])print(doc));
		
		this.close();
		
		if (chkBrowser.checked)
		{
			char* stringz = toStringz(this.editFilename.text);
			ShellExecuteA(null, "open", stringz, null, null, SW_SHOWNORMAL);
		}
		
		ConfigFile.setValue("exportOpenBrowser", chkBrowser.checked);
	}
	
	private void browseClick(Object sender, EventArgs ea)
	{
		auto fp = new tango.io.FilePath.FilePath(this.editFilename.text);
		SaveFileDialog fd = new SaveFileDialog();
		fd.initialDirectory = fp.path();
		fd.fileName = fp.file();
		fd.filter = FILE_FILTER;
		fd.defaultExt = DEFAULT_SAVE_EXTENSION;
		auto res = fd.showDialog();
		char[] normalizedPath = PU.normalize(fd.fileName);
		
		debug tango.io.Stdout.Stdout(normalizedPath).newline;
		
		if (res !is dfl.base.DialogResult.OK)
			return;
		
		this.editFilename.text = normalizedPath;
	}
	
	private void initializeExportHTML()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.6pre4 code begins here.
		//~DFL Form
		controlBox = false;
		formBorderStyle = dfl.all.FormBorderStyle.FIXED_SINGLE;
		maximizeBox = false;
		minimizeBox = false;
		showInTaskbar = false;
		startPosition = dfl.all.FormStartPosition.CENTER_PARENT;
		text = "Export to HTML";
		topMost = true;
		clientSize = dfl.all.Size(354, 144);
		//~DFL dfl.groupbox.GroupBox=groupBox1
		groupBox1 = new dfl.groupbox.GroupBox();
		groupBox1.name = "groupBox1";
		groupBox1.dock = dfl.all.DockStyle.TOP;
		groupBox1.text = "Site Title";
		groupBox1.bounds = dfl.all.Rect(0, 0, 354, 50);
		groupBox1.parent = this;
		//~DFL dfl.textbox.TextBox=editTitle
		editTitle = new dfl.textbox.TextBox();
		editTitle.name = "editTitle";
		editTitle.dock = dfl.all.DockStyle.TOP;
		editTitle.bounds = dfl.all.Rect(8, 19, 338, 23);
		editTitle.parent = groupBox1;
		//~DFL dfl.panel.Panel=panel2
		panel2 = new dfl.panel.Panel();
		panel2.name = "panel2";
		panel2.dock = dfl.all.DockStyle.TOP;
		panel2.bounds = dfl.all.Rect(0, 50, 354, 6);
		panel2.parent = this;
		//~DFL dfl.groupbox.GroupBox=groupBox2
		groupBox2 = new dfl.groupbox.GroupBox();
		groupBox2.name = "groupBox2";
		groupBox2.dock = dfl.all.DockStyle.TOP;
		groupBox2.text = "Filename";
		groupBox2.bounds = dfl.all.Rect(0, 56, 354, 50);
		groupBox2.parent = this;
		//~DFL dfl.button.Button=btnBrowse
		btnBrowse = new dfl.button.Button();
		btnBrowse.name = "btnBrowse";
		btnBrowse.dock = dfl.all.DockStyle.RIGHT;
		btnBrowse.text = "Browse";
		btnBrowse.bounds = dfl.all.Rect(271, 19, 75, 23);
		btnBrowse.parent = groupBox2;
		//~DFL dfl.panel.Panel=panel3
		panel3 = new dfl.panel.Panel();
		panel3.name = "panel3";
		panel3.dock = dfl.all.DockStyle.RIGHT;
		panel3.bounds = dfl.all.Rect(265, 19, 6, 23);
		panel3.parent = groupBox2;
		//~DFL dfl.textbox.TextBox=editFilename
		editFilename = new dfl.textbox.TextBox();
		editFilename.name = "editFilename";
		editFilename.dock = dfl.all.DockStyle.TOP;
		editFilename.bounds = dfl.all.Rect(8, 19, 257, 23);
		editFilename.parent = groupBox2;
		//~DFL dfl.button.Button=btnExport
		btnExport = new dfl.button.Button();
		btnExport.name = "btnExport";
		btnExport.text = "Export";
		btnExport.bounds = dfl.all.Rect(8, 116, 75, 23);
		btnExport.parent = this;
		//~DFL dfl.button.Button=btnCancel
		btnCancel = new dfl.button.Button();
		btnCancel.name = "btnCancel";
		btnCancel.text = "Cancel";
		btnCancel.bounds = dfl.all.Rect(88, 116, 75, 23);
		btnCancel.parent = this;
		//~DFL dfl.button.CheckBox=chkBrowser
		chkBrowser = new dfl.button.CheckBox();
		chkBrowser.name = "chkBrowser";
		chkBrowser.text = "Open in Browser";
		chkBrowser.checkState = dfl.all.CheckState.CHECKED;
		chkBrowser.bounds = dfl.all.Rect(248, 116, 99, 23);
		chkBrowser.parent = this;
		//~Entice Designer 0.8.6pre4 code ends here.
	}
}

