module pages.AppearancePanel;

/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;


class AppearancePanel: dfl.panel.Panel
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.groupbox.GroupBox groupBox2;
	dfl.button.CheckBox checkBox2;
	dfl.button.CheckBox checkBox3;
	dfl.button.CheckBox checkBox5;
	dfl.groupbox.GroupBox groupBox3;
	dfl.button.RadioButton radioButton1;
	dfl.button.RadioButton radioButton2;
	dfl.button.RadioButton radioButton3;
	dfl.button.RadioButton radioButton4;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeAppearancePanel();
		
		//@  Other AppearancePanel initialization code here.
		
	}
	
	
	private void initializeAppearancePanel()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Panel
		name = "AppearancePanel";
		foreColor = dfl.all.Color(50, 255, 0);
		bounds = dfl.all.Rect(0, 0, 384, 336);
		//~DFL dfl.groupbox.GroupBox=groupBox2
		groupBox2 = new dfl.groupbox.GroupBox();
		groupBox2.name = "groupBox2";
		groupBox2.dock = dfl.all.DockStyle.TOP;
		groupBox2.text = "Combined Play && Pause Button";
		groupBox2.bounds = dfl.all.Rect(0, 0, 384, 64);
		groupBox2.parent = this;
		//~DFL dfl.button.CheckBox=checkBox2
		checkBox2 = new dfl.button.CheckBox();
		checkBox2.name = "checkBox2";
		checkBox2.text = "normal layout";
		checkBox2.bounds = dfl.all.Rect(-240, -237, 368, 23);
		checkBox2.parent = groupBox2;
		//~DFL dfl.button.CheckBox=checkBox3
		checkBox3 = new dfl.button.CheckBox();
		checkBox3.name = "checkBox3";
		checkBox3.dock = dfl.all.DockStyle.TOP;
		checkBox3.text = "normal layout";
		checkBox3.bounds = dfl.all.Rect(8, 19, 368, 16);
		checkBox3.parent = groupBox2;
		//~DFL dfl.button.CheckBox=checkBox5
		checkBox5 = new dfl.button.CheckBox();
		checkBox5.name = "checkBox5";
		checkBox5.dock = dfl.all.DockStyle.TOP;
		checkBox5.text = "shade layout";
		checkBox5.bounds = dfl.all.Rect(8, 35, 368, 23);
		checkBox5.parent = groupBox2;
		//~DFL dfl.groupbox.GroupBox=groupBox3
		groupBox3 = new dfl.groupbox.GroupBox();
		groupBox3.name = "groupBox3";
		groupBox3.dock = dfl.all.DockStyle.TOP;
		groupBox3.text = "Button Glow";
		groupBox3.bounds = dfl.all.Rect(0, 64, 384, 116);
		groupBox3.parent = this;
		//~DFL dfl.button.RadioButton=radioButton1
		radioButton1 = new dfl.button.RadioButton();
		radioButton1.name = "radioButton1";
		radioButton1.dock = dfl.all.DockStyle.TOP;
		radioButton1.enabled = false;
		radioButton1.text = "Off";
		radioButton1.bounds = dfl.all.Rect(8, 19, 368, 23);
		radioButton1.parent = groupBox3;
		//~DFL dfl.button.RadioButton=radioButton2
		radioButton2 = new dfl.button.RadioButton();
		radioButton2.name = "radioButton2";
		radioButton2.dock = dfl.all.DockStyle.TOP;
		radioButton2.text = "Hold";
		radioButton2.bounds = dfl.all.Rect(8, 42, 368, 23);
		radioButton2.parent = groupBox3;
		//~DFL dfl.button.RadioButton=radioButton3
		radioButton3 = new dfl.button.RadioButton();
		radioButton3.name = "radioButton3";
		radioButton3.dock = dfl.all.DockStyle.TOP;
		radioButton3.text = "Bounce";
		radioButton3.bounds = dfl.all.Rect(8, 65, 368, 23);
		radioButton3.parent = groupBox3;
		//~DFL dfl.button.RadioButton=radioButton4
		radioButton4 = new dfl.button.RadioButton();
		radioButton4.name = "radioButton4";
		radioButton4.dock = dfl.all.DockStyle.TOP;
		radioButton4.text = "Flash";
		radioButton4.bounds = dfl.all.Rect(8, 88, 368, 23);
		radioButton4.parent = groupBox3;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

