/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

module pages.beatvis;

import dfl.all;
private import Text = tango.text.Util;
private import tango.io.File;
private import tango.net.http.HttpGet;

class BeatVis: dfl.panel.Panel
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.textbox.TextBox textBox1;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeCproGeneral();
		
		//@  Other CproGeneral initialization code here.
		
	}

	
	private void initializeCproGeneral()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.6pre4 code begins here.
		//~DFL Panel
		name = "BeatVis";
		tag = new dfl.all.StringObject("node:ClassicPro/Visualization/BeatVis");
		bounds = dfl.all.Rect(0, 0, 448, 336);
		//~DFL dfl.textbox.TextBox=textBox1
		textBox1 = new dfl.textbox.TextBox();
		textBox1.name = "textBox1";
		textBox1.dock = dfl.all.DockStyle.FILL;
		textBox1.tag = new dfl.all.StringObject("blob:customvis");
		textBox1.multiline = true;
		textBox1.bounds = dfl.all.Rect(0, 0, 448, 336);
		textBox1.parent = this;
		//~Entice Designer 0.8.6pre4 code ends here.
	}
}

