module pages.ColorsPanel;

/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;

class ColorsPanel: dfl.panel.Panel
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.groupbox.GroupBox groupBox1;
	dfl.treeview.TreeView treeView1;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeColorsPanel();

		//@  Other ColorsPanel initialization code here.
		
	}
	
	
	private void initializeColorsPanel()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Panel
		name = "ColorsPanel";
		bounds = dfl.all.Rect(0, 0, 368, 328);
		//~DFL dfl.groupbox.GroupBox=groupBox1
		groupBox1 = new dfl.groupbox.GroupBox();
		groupBox1.name = "groupBox1";
		groupBox1.dock = dfl.all.DockStyle.RIGHT;
		groupBox1.bounds = dfl.all.Rect(168, 0, 200, 328);
		groupBox1.parent = this;
		//~DFL dfl.treeview.TreeView=treeView1
		treeView1 = new dfl.treeview.TreeView();
		treeView1.name = "treeView1";
		treeView1.bounds = dfl.all.Rect(24, 48, 96, 264);
		treeView1.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

