/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

module pages.CproGeneral;

import dfl.all;
private import Text = tango.text.Util;
private import tango.io.File;
private import tango.net.http.HttpGet;

class CproGeneral: dfl.panel.Panel
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.groupbox.GroupBox groupBox1;
	dfl.combobox.ComboBox _version;
	dfl.panel.Panel panel2;
	dfl.button.Button getList;
	dfl.label.Label label1;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeCproGeneral();
		
		//@  Other CproGeneral initialization code here.
		
		getList.click ~= &getVersionList;
		
		populateVersions();
		
	}
	
	private void getVersionList(Object sender, EventArgs ea)
	{
		getList.enabled(false);
		
		auto page = new HttpGet("http://www.skinconsortium.com/updatemanager/cproversions.lst");
		if (page.getStatus() < 400)
		{
			File vlist = new File("templates/cproversions.lst");
			vlist.write(page.read());
			
			populateVersions();
		}
		getList.enabled(true);
		_version.selectedIndex(_version.items.length-1);
	}
	
	private void populateVersions()
	{
		_version.items.clear;
		
		File vlist = new File("templates/cproversions.lst");
		
		foreach(line;Text.lines(cast(char[])vlist.read()))
		{
			_version.items.add(line);
		}
	}
	
	
	private void initializeCproGeneral()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Panel
		name = "CproGeneral";
		tag = new dfl.all.StringObject("node:ClassicPro");
		bounds = dfl.all.Rect(0, 0, 448, 336);
		//~DFL dfl.groupbox.GroupBox=groupBox1
		groupBox1 = new dfl.groupbox.GroupBox();
		groupBox1.name = "groupBox1";
		groupBox1.dock = dfl.all.DockStyle.TOP;
		groupBox1.tag = new dfl.all.StringObject("flat");
		groupBox1.text = "Minimum required ClassicPro version for this skin";
		groupBox1.bounds = dfl.all.Rect(0, 0, 448, 48);
		groupBox1.parent = this;
		//~DFL dfl.combobox.ComboBox=_version
		_version = new dfl.combobox.ComboBox();
		_version.name = "_version";
		_version.dock = dfl.all.DockStyle.LEFT;
		_version.tag = new dfl.all.StringObject("attrib");
		_version.bounds = dfl.all.Rect(8, 19, 112, 21);
		_version.parent = groupBox1;
		//~DFL dfl.panel.Panel=panel2
		panel2 = new dfl.panel.Panel();
		panel2.name = "panel2";
		panel2.dock = dfl.all.DockStyle.LEFT;
		panel2.bounds = dfl.all.Rect(120, 19, 10, 21);
		panel2.parent = groupBox1;
		//~DFL dfl.button.Button=getList
		getList = new dfl.button.Button();
		getList.name = "getList";
		getList.dock = dfl.all.DockStyle.LEFT;
		getList.text = "refresh version list";
		getList.bounds = dfl.all.Rect(130, 19, 115, 21);
		getList.parent = groupBox1;
		//~DFL dfl.label.Label=label1
		label1 = new dfl.label.Label();
		label1.name = "label1";
		label1.dock = dfl.all.DockStyle.RIGHT;
		label1.text = "(requires internet connection)";
		label1.textAlign = dfl.all.ContentAlignment.MIDDLE_RIGHT;
		label1.bounds = dfl.all.Rect(292, 19, 148, 21);
		label1.parent = groupBox1;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

