module about;

/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import global;

import dfl.all;
import dfl.internal.winapi;
//import dfl.internal._stdcwindows;

const int ID_ABOUT = 201;

class About: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.picturebox.PictureBox pictureBox1;
	dfl.label.Label label2;
	dfl.button.Button btnClose;
	dfl.label.Label label4;
	dfl.label.Label label5;
	dfl.label.Label label6;
	dfl.label.Label link;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeAbout();

		//@  Other About initialization code here.
		pictureBox1.image = Application.resources.getBitmap(ID_ABOUT);
		btnClose.click ~= &closeAboutWnd;
		link.cursor = Cursors.hand;
		link.click ~= &openLink;
		label2.text = "version " ~ VERSION ~" build "~ buildstamp_char ~" - "~ DATE;
	}
	
	private void closeAboutWnd(Control c, EventArgs ea)
	{
		this.close();
	}
	
	private void openLink(Control c, EventArgs ea)
	{
		ShellExecuteA(null, null, "http://www.skinconsortium.com", null, ".", SW_SHOWNORMAL);
	}
	
	private void initializeAbout()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		formBorderStyle = dfl.all.FormBorderStyle.FIXED_TOOLWINDOW;
		showInTaskbar = false;
		startPosition = dfl.all.FormStartPosition.CENTER_PARENT;
		text = "About";
		clientSize = dfl.all.Size(282, 232);
		//~DFL dfl.picturebox.PictureBox=pictureBox1
		pictureBox1 = new dfl.picturebox.PictureBox();
		pictureBox1.name = "pictureBox1";
		pictureBox1.dock = dfl.all.DockStyle.TOP;
		pictureBox1.sizeMode = dfl.all.PictureBoxSizeMode.CENTER_IMAGE;
		pictureBox1.bounds = dfl.all.Rect(0, 0, 282, 96);
		pictureBox1.parent = this;
		//~DFL dfl.label.Label=label2
		label2 = new dfl.label.Label();
		label2.name = "label2";
		label2.dock = dfl.all.DockStyle.TOP;
		label2.text = "version 0.1";
		label2.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
		label2.bounds = dfl.all.Rect(0, 96, 282, 24);
		label2.parent = this;
		//~DFL dfl.button.Button=btnClose
		btnClose = new dfl.button.Button();
		btnClose.name = "btnClose";
		btnClose.text = "Close";
		btnClose.bounds = dfl.all.Rect(8, 202, 267, 24);
		btnClose.parent = this;
		//~DFL dfl.label.Label=label4
		label4 = new dfl.label.Label();
		label4.name = "label4";
		label4.dock = dfl.all.DockStyle.TOP;
		label4.text = "written by Martin Pöhlmann";
		label4.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
		label4.bounds = dfl.all.Rect(0, 120, 282, 16);
		label4.parent = this;
		//~DFL dfl.label.Label=label5
		label5 = new dfl.label.Label();
		label5.name = "label5";
		label5.dock = dfl.all.DockStyle.TOP;
		label5.text = "using Tango/DFL for D";
		label5.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
		label5.bounds = dfl.all.Rect(0, 136, 282, 16);
		label5.parent = this;
		//~DFL dfl.label.Label=label6
		label6 = new dfl.label.Label();
		label6.name = "label6";
		label6.dock = dfl.all.DockStyle.TOP;
		label6.text = "\&copy; 2008-2009 Skin Consortium";
		label6.textAlign = dfl.all.ContentAlignment.BOTTOM_CENTER;
		label6.bounds = dfl.all.Rect(0, 152, 282, 24);
		label6.parent = this;
		//~DFL dfl.label.Label=link
		link = new dfl.label.Label();
		link.name = "link";
		link.dock = dfl.all.DockStyle.TOP;
		link.font = new dfl.all.Font("Microsoft Sans Serif", 9f, dfl.all.FontStyle.UNDERLINE);
		link.foreColor = dfl.all.Color(0, 0, 255);
		link.text = "http://www.skinconsortium.com";
		link.textAlign = dfl.all.ContentAlignment.BOTTOM_CENTER;
		link.bounds = dfl.all.Rect(0, 176, 282, 18);
		link.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

